version: "3.6"
services:
  indexer-base:
    container_name: mainnet-indexer-base
    build:
      context: .
      dockerfile: ./apps/indexer-base/Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: mainnet.env
  indexer-balance:
    container_name: mainnet-indexer-balance
    build:
      context: .
      dockerfile: ./apps/indexer-balance/Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: mainnet.env
  redis:
    container_name: mainnet-redis
    image: redis:7.2-alpine
    command: redis-server --appendonly yes --appendfsync always
    restart: always
    volumes:
      - redis-data:/mnt/redis

volumes:
  redis-data:
