name = "app"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.testnet.vars]
NEXT_PUBLIC_NETWORK_ID = "testnet"
NEXT_PUBLIC_BOS_NETWORK = "testnet"
NEXT_PUBLIC_ACCOUNT_ID = "nearblocks.testnet"
NEXT_PUBLIC_OG_URL = "https://meta.nearblocks.io/api"
NEXT_PUBLIC_MAINNET_URL = "https://nearblocks.io"
NEXT_PUBLIC_TESTNET_URL = "https://testnet.nearblocks.io"
NEXT_PUBLIC_GTM_ID = "GTM-P285ZPV2"
NEXT_PUBLIC_USER_API_URL = "https://api.exploreblocks.io/api/"
NEXT_PUBLIC_USER_DASHBOARD_URL = "https://dash.nearblocks.io/"
NEXT_PUBLIC_API_URL = "https://api-testnet.nearblocks.io/v1/"
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAAkRNqQmMaemLDOQ"
NEXT_PUBLIC_REOWN_PROJECT_ID = "5690251ad29b1ed10f9a41bf343964e1"
API_URL = "https://api-testnet.nearblocks.io/v1/"
